baseURL = 'https://alythical.github.io'
languageCode = 'en-us'
title = 'alythical'
theme = 'paper'

[params]
color = 'light'

github = 'alythical'

avatar = 'https://avatars.githubusercontent.com/u/68250402?v=4'
name = 'alythical'
bio = ''

monoDarkIcon = true

[menu]
[[menu.main]]
name = 'posts'
url = '/post/'
weight = 1